language: node_js
node_js:
 - "7.9.0"
 - "6.10.2"
 - "5.12.0"
script:
 - "npm run build"
 - "npm run test+coverage"
after_script:
  - "cat coverage/lcov.info"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
env:
  global:
    # NPM_AUTH_TOKEN
    secure: goIuZqbvukt7LXRKzEqXhKb9xqizr7ikxm8KRD/mUiGBJ1xikehQFKSTulJoPfsyOPe3WOfhq1aKZwRCzDXbqt9oSbJoMhgSTn/jB274WYv8VuTWZQUVIeruba0ma1spyQSag1o+WaDYVRUfy1mEkUX7jQJY4lxEUJP1bFHREig=
deploy:
- provider: script
  script: ./.travis/deploy.py
  on:
    condition: '"${TRAVIS_NODE_VERSION}" == "7.9.0"' 
    tags: true
